### ISSUE TITLE
Add support for 'asyncRequest' function

### ISSUE THREAD

**Issue by ewefie** [grafana/k6-jslib-httpx#13]
Now when 'k6/http' got support [for asynchronous requests](https://k6.io/docs/javascript-api/k6-http/asyncrequest/), I'd like 'httpx' to support them as well.

**Comment by ewefie** [comment]
I've opened a PR https://github.com/grafana/k6-jslib-httpx/pull/14

**Comment by sniku** [comment]
PR merged; thank you for contributing :heart: 
We are awaiting jslib release: https://github.com/grafana/jslib.k6.io/pull/97
