### ISSUE TITLE
When doing GET, params don't work as expected

### ISSUE THREAD

**Issue by dmlundeby** [grafana/k6-jslib-httpx#7]
I'd like to do a GET request with params, like:

```js
import { Httpx } from 'https://jslib.k6.io/httpx/0.0.6/index.js';
import http from "k6/http";

const session = new Httpx({ baseURL: 'https://test.k6.io/' })

export default function () {
    session.get('/nonexisting', { responseCallback: http.expectedStatuses(404) })
}
```

This does not work. It turns out we need an empty body as second argument (unlike `http.get`):

```js
session.get('/nonexisting', null, { responseCallback: http.expectedStatuses(404) })
```

The error seems to be here: https://github.com/grafana/k6-jslib-httpx/blob/bf9af24ee1d51de61c8808bd07efd0e76979e5dd/src/httpx.js#L205
The same goes for HEAD requests.

**Comment by sniku** [comment]
All http methods in `httpx` library take the same parameters.
While GET and HEAD _should_ not need body, there are APIs out there that require it.
